# -*- coding: utf-8 -*-
"""
Created on Tue Jul 18 18:26:38 2017

@author: mnmg91
"""
'''This module provide some metrics to quantify the result generated by the 
    Behaviour_Rule module. 

An overview of the metrics:
--------------------------
HHI :  The Herfindahl-Hirschman index (HHI) is a commonly accepted measure of 
       market concentration. It is calculated by squaring the market share of each firm
       competing in a market, and then summing the resulting numbers. Range from 0 to 1. 
       The closer a market is to being a monopoly, the higher the HHI (and the lower its 
       competition). The US Department of Justice and the Federal Trade Commission generally 
       classify markets into three types: 
           Unconcentrated markets: HHI < 0.15; 
           Moderately Concentrated: HHI between 0.15 and 0.25; 
           Highly Concentrated: HHI > 0.25. 
-------------------------------------------------------------------------------
The metric is usually used in combination with the functions in the Behaviour_Rule module,
    e.g. HHI(sim_revive_inn(popgrow(),4,0,20,True)[:,1945])
         HHI(sim_random_inn(popgrow(),4,0,20,10,True)[:,popgrow().index(max(popgrow()))])
'''
def HHI(target_array):
    '''Parameters:
       -----------
        target_array: numpy.ndarray 
                      It should be a specific array of interest. Usually can be 
                      extracted from the whole distribution (matrix version) output 
                      of the functions in Behaviour_Rule module. 
    '''
    share = target_array/float(sum(target_array))
    HHI = sum(share**2)
    return HHI